= ee-central.io Configuration Project

This project holds all the configuration and editable content of the projects published as a demo at https://bit.ly/ee-io (and later will be published under ee-central.io domain).

The application is configured to read the pages and configuration from this repository. For pages, it uses GitHub API to convert markup documents (AsciiDoc, Markdown, ...) into html content. Therefore the page will look similar to what you get when you preview the page in the browser on GitHub site (except some CSS styles applied).

In order to preview the pages locally, before the pages are commited to the Github repository, execute

    mvn package

Afterwards, adoc files in `pages` folder will be available in `target/generated-adoc/pages-preview/`. Note that this generator runs AsciiDoc generator directly and supports more features than Github generator (e.g. it will properly include files when include directive is used, while Github will just produce link to the included file). Therefore generated pages may not always look like they appear finally on the site.

You can also link the application using `javaeeio_devel_pages_root` property (and devel profile) to pages-embed, where is plain generated html output, without html header and footer. Again, note that such pages may support more Asciidoc options than supported by the real site.

== How to contribute

The preferred way to accept contribution is by pull requests. For the main repository https://github.com/jcpevangelists/javaee.io.config/[jcpevangelists/javaee.io.config], edit pages in `pages` folder (information below), and create a pull request.

Information on which content is missing and planned to be added to the site is available on https://drive.google.com/drive/u/0/folders/0B3aSdhyM5-5CZGFYTmJwcjc3Qmc[this public google docucoment].

== Pages

Site pages are configured by files in `pages` folder. They can be in any markup supported by GitHub, but adoc format is preferred.

Generally it should be enough to preview the pages in your fork using GitHub site, as this is very close to how they will look like in the application. When the main repository is updated (usually when a pull request is accepted), then the application is automatically updated with recent changes in the repository.

=== Page configuration files

A page is configured by:

 - markup file (e.g. `.adoc`) - it defines the page body and name
 - yaml file (e.g. `.adoc.yaml`) - it has the same name as the markup file plus `.yaml`, defines additional attributes of the page in yaml format

Yaml configuration contains:

- h1 - main header of the page
- h2 - secondary (longer) header of the page

=== ADOC syntax specific

==== Links to other pages

When referring to another page, always use external links, such as `\link:mission.adoc[JavaEE.io]`. Otherwise the links will not work in the application.
