= What We are Doing

* We are continuing to enthusiastically evangelize Java EE, including Java EE 8.
* We are strongly supporting active Java EE 8 JSRs like CDI 2 led by companies like Red Hat.
* We are lobbying Oracle to fulfil its commitments toward Java EE 8 through all channels available to us.
* We are keeping all Java EE 8 expert group discussions active, in many cases despite lack of activity from Oracle.
* We are moving ahead Java EE 8 reference implementations, TCKs and specification documents through open source in many cases despite inactive Oracle specification leads. Our biggest challenge in this regard is access to the TCK and getting our work accepted by Oracle specification leads.
* We are exploring whether some inactive Oracle led JSRs can switch ownership to us or vendors like Red Hat, IBM, Tomitribe or Payara. Our biggest challenge in this regard is getting Oracle to relinquish control of JSRs they are clearly not delivering on.
* In conjunction to the above in the interim we will provide the functionality that should be standardized in Java EE through open source. We will work with vendors like Oracle, Red Hat, IBM, Tomitribe and Payara to include these features in their Java EE runtimes out-of-the-box. We will provide these features to vendors completely free of charge with the clear goal of eventual standardization via the JCP.
